---
- name: Name
  shell: uname -a
  register: uname
  ignore_errors: yes
- debug: msg={{uname.stdout}}

- set_fact:
    var1: "{{uname.stdout}}"
- template:
    src: "myrole.j2"
    dest: "/home/cloud_user/RohithKarraInterview/roles/myrole/files/my-template.txt"
